name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    name: Set up Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge, defaults
          channel-priority: true
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true

      - name: Install distributions
        shell: bash -l {0}
        run: |
          conda install pip
          pip install -e .[test]
          python --version
          conda list
          pip freeze
      - name: Run tests
        shell: bash -l {0}
        run: |
          python -m pytest -vv --cov=distributions --cov-report=term --cov-report=xml tests
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
